---
- name: Install/upgrade Homebrew cask applications
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: "{{ 'upgraded' if upgrade_packages | bool else 'present' }}"
  loop: "{{ homebrew_casks + homebrew_casks_extra }}"
  when: (homebrew_casks + homebrew_casks_extra) | length > 0
