---
- name: Update Homebrew index
  community.general.homebrew:
    update_homebrew: true
    path: "{{ homebrew_path }}"
  changed_when: false

- name: Add Homebrew taps
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
    path: "{{ homebrew_path }}"
  loop: "{{ homebrew_taps + homebrew_taps_extra }}"
  when: (homebrew_taps + homebrew_taps_extra) | length > 0

- name: Install/upgrade Homebrew formulae
  community.general.homebrew:
    name: "{{ item }}"
    state: "{{ 'latest' if upgrade_packages | bool else 'present' }}"
    path: "{{ homebrew_path }}"
  loop: "{{ homebrew_formulae + homebrew_formulae_extra }}"
  when: (homebrew_formulae + homebrew_formulae_extra) | length > 0
